controller_manager:
  ros__parameters:
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["wheel_l_joint"]
    right_wheel_names: ["wheel_r_joint"]

    wheel_separation: 0.126
    wheel_radius: 0.0325

    odom_frame_id: odom
    base_frame_id: base_link

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    # Velocity and acceleration limits
    # # Whenever a min_* is unspecified, default to -max_*
    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: true
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: 100.0
    # linear.x.min_velocity: -100.0
    # linear.x.max_acceleration: 100.0
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    # angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: 100.0
    # angular.z.min_velocity: -100.0
    # angular.z.max_acceleration: 100.0
    # angular.z.min_acceleration: -100.0
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0
